import{TuneSearch}from'./tune-search.js';import{TheSessionProvider}from'./providers/thesession.js';import{GavinHeneghanProvider}from'./providers/gavin-heneghan.js';import{MuseTrainerProvider}from'./providers/musetrainer.js';
const $=id=>document.getElementById(id),engine=new TuneSearch({providers:[TheSessionProvider,GavinHeneghanProvider,MuseTrainerProvider]}),status=$('status'),results=$('results');let synth=null,audioContext=null;const instruments=[['auto','Automatisch',null],['piano','Klavier',0],['violin','Violine',40],['viola','Viola',41],['cello','Violoncello',42],['contrabass','Kontrabass',43],['flute','Flöte',73],['oboe','Oboe',68],['clarinet','Klarinette',71],['bassoon','Fagott',70],['trumpet','Trompete',56],['horn','Horn',60]];
const esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),STORE='tune-search-lists-v1',STATE='tune-search-state-v1';
let lists=(()=>{try{return JSON.parse(localStorage.getItem(STORE)||'{}')}catch{return {}}})();let lastHits=[];let memory=(()=>{try{return JSON.parse(localStorage.getItem(STATE)||'{}')}catch{return {}}})();const saveLists=()=>localStorage.setItem(STORE,JSON.stringify(lists));const saveMemory=()=>{memory={query:$('query').value,type:$('type').value,key:$('key').value,meter:$('meter').value,instrument:$('instrument').value,activeList:$('listSelect').value,sources:[...document.querySelectorAll('[data-source]:checked')].map(x=>x.value),lastHits};localStorage.setItem(STATE,JSON.stringify(memory))};
async function stop(){if(synth)try{synth.stop()}catch(_){}}async function playMidi(hit,button){await stop();const spec=hit.formats?.midi;if(!spec)throw new Error('Keine MIDI-Datei vorhanden.');const url=typeof spec==='string'?spec:spec.url;if(!url)throw new Error('MIDI-Adresse fehlt.');const r=await fetch(url);if(!r.ok)throw new Error('MIDI-Datei konnte nicht geladen werden ('+r.status+').');const data=await r.arrayBuffer();if(!window.Midi)throw new Error('MIDI-Parser ist nicht geladen.');const midi=new window.Midi(data);if(!audioContext)audioContext=new(window.AudioContext||window.webkitAudioContext)();if(audioContext.state!=='running')await audioContext.resume();const start=audioContext.currentTime+.05,osc=[];const programToWave=p=>p>=40&&p<=51?'sawtooth':p>=72&&p<=79?'sine':p>=56&&p<=71?'square':'triangle';for(const track of midi.tracks){const wave=programToWave(track.instrument?.number??0);for(const note of track.notes){const o=audioContext.createOscillator(),g=audioContext.createGain();o.type=wave;o.frequency.value=440*Math.pow(2,(note.midi-69)/12);g.gain.setValueAtTime(0,start+note.time);g.gain.linearRampToValueAtTime(Math.max(.015,note.velocity*.08),start+note.time+.01);g.gain.setValueAtTime(Math.max(.015,note.velocity*.08),start+note.time+Math.max(.02,note.duration-.03));g.gain.linearRampToValueAtTime(0,start+note.time+note.duration);o.connect(g).connect(audioContext.destination);o.start(start+note.time);o.stop(start+note.time+note.duration+.03);osc.push(o)}}synth={stop(){for(const o of osc)try{o.stop()}catch(_){}}};button.textContent='Läuft …'}

function abcWithInstrument(abc){const selected=$('instrument').value;if(selected==='auto')return String(abc);const chosen=instruments.find(x=>x[0]===selected)||instruments.find(x=>x[0]==='piano');const lines=String(abc).split('\n').filter(line=>!/^%%MIDI program\s+/i.test(line));let v=lines.findIndex(line=>/^V:1(?:\s|$)/.test(line));if(v>=0){lines[v]=lines[v].replace(/\s+(?:name|nm|subname|snm)="[^"]*"/gi,'')+' name="'+chosen[1]+'"';lines.splice(v,0,'%%MIDI program '+chosen[2])}else{const k=lines.findIndex(line=>/^K:/i.test(line));lines.splice(k>=0?k+1:0,0,'%%MIDI program '+chosen[2])}return lines.join('\n')}async function preview(hit,box,button){if(!hit.abc)throw new Error('Für diese Quelle ist die ABC-Vorschau nicht verfügbar.');await stop();document.querySelectorAll('.preview').forEach(x=>x.innerHTML='');if(!audioContext)audioContext=new(window.AudioContext||window.webkitAudioContext)();if(audioContext.state!=='running')await audioContext.resume();const r=ABCJS.renderAbc(box,abcWithInstrument(hit.abc),{responsive:'resize'});if(!r[0])throw new Error('ABC konnte nicht gerendert werden.');synth=new ABCJS.synth.CreateSynth();await synth.init({audioContext,visualObj:r[0],options:{chordsOff:true}});await synth.prime();await synth.start();button.textContent='Läuft …'}
async function previewMusicXML(hit,box,button){try{
 await stop();document.querySelectorAll('.preview').forEach(x=>x.innerHTML='');
 const spec=hit.formats?.musicxml,url=typeof spec==='string'?spec:spec?.url;
 if(!url)throw new Error('MusicXML-Adresse fehlt.');
 const r=await fetch(url);if(!r.ok)throw new Error('MusicXML konnte nicht geladen werden ('+r.status+').');
 const tk=await ensureVerovio(),buffer=await r.arrayBuffer();
 tk.setOptions({pageWidth:1800,pageHeight:2450,scale:32,footer:'none'});
 const compressed=spec?.compressed||/\.mxl(?:$|[?#])/i.test(url);
 let loaded;
 if(compressed){
  if(typeof tk.loadZipDataBase64!=='function')throw new Error('Verovio bietet keinen MXL-Loader.');
  try{const bytes=new Uint8Array(buffer);let binary='';for(let i=0;i<bytes.length;i+=0x8000)binary+=String.fromCharCode(...bytes.subarray(i,i+0x8000));loaded=tk.loadZipDataBase64(btoa(binary))}catch(e){throw new Error('MXL-Import: '+errorText(e))}
 }else{
  try{loaded=tk.loadData(new TextDecoder('utf-8').decode(buffer))}catch(e){throw new Error('MusicXML-Import: '+errorText(e))}
 }
 if(loaded===false)throw new Error('Verovio konnte die MusicXML-Datei nicht lesen.');
 const svg=tk.renderToSVG(1,false);if(!svg)throw new Error('Verovio hat kein Notenbild erzeugt.');box.innerHTML=svg;
 let midi64;try{midi64=tk.renderToMIDI()}catch(e){throw new Error('MIDI-Erzeugung: '+errorText(e))}
 if(!midi64)throw new Error('Verovio hat keine MIDI-Daten erzeugt.');
 const raw=atob(midi64),bytes=new Uint8Array(raw.length);for(let i=0;i<raw.length;i++)bytes[i]=raw.charCodeAt(i);
 const midiUrl=URL.createObjectURL(new Blob([bytes],{type:'audio/midi'}));try{await playMidi({formats:{midi:{url:midiUrl}}},button)}finally{setTimeout(()=>URL.revokeObjectURL(midiUrl),1000)}
}catch(e){throw new Error(errorText(e))}}
function errorText(e){if(e instanceof Error&&e.message)return e.message;if(typeof e==='string')return e;try{const j=JSON.stringify(e);if(j&&j!=='{}')return j}catch(_){}return 'Unbekannter MusicXML-Fehler ('+Object.prototype.toString.call(e)+')'}
async function previewHit(hit,box,button){if(hit.formats?.abc||hit.abc)return preview(hit,box,button);if(hit.formats?.musicxml)return previewMusicXML(hit,box,button);if(hit.formats?.midi)return playMidi(hit,button);throw new Error('Keine vorhörbare Datei vorhanden.')}
function refreshLists(preferredName){const current=preferredName||$('listSelect').value||memory.activeList;const names=Object.keys(lists).sort((a,b)=>a.localeCompare(b));$('listSelect').innerHTML=names.map(n=>'<option>'+esc(n)+'</option>').join('');if(current&&names.includes(current))$('listSelect').value=current;const name=$('listSelect').value,items=lists[name]||[];memory.activeList=name||'';localStorage.setItem(STATE,JSON.stringify({...memory,activeList:memory.activeList}));$('saved').innerHTML=items.map((h,i)=>'<div class="saved"><strong>'+esc(h.title)+'</strong> <span class="meta">'+esc([h.type,h.key,h.meter].filter(Boolean).join(' · '))+'</span><div class="actions"><button data-play="'+i+'">▶ Vorhören</button><button data-stop="'+i+'">■ Stop</button><button data-remove="'+i+'">Entfernen</button></div><div class="preview" data-preview="'+i+'"></div></div>').join('');$('saved').querySelectorAll('[data-play]').forEach(b=>b.onclick=()=>previewHit(items[+b.dataset.play],$('saved').querySelector('[data-preview="'+b.dataset.play+'"]'),b).catch(e=>{console.error(e);status.textContent='Vorhörfehler: '+(e?.message||String(e)||'Unbekannter Fehler')}));$('saved').querySelectorAll('[data-stop]').forEach(b=>b.onclick=async()=>{await stop();const p=$('saved').querySelector('[data-play="'+b.dataset.stop+'"]');if(p)p.textContent='▶ Vorhören'});$('saved').querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{lists[name].splice(+b.dataset.remove,1);saveLists();refreshLists(name)})}
function add(hit){const name=$('listSelect').value;if(!name){status.textContent='Bitte zuerst eine Suchliste anlegen.';return}lists[name]??=[];if(!lists[name].some(x=>x.providerId===hit.providerId&&x.id===hit.id))lists[name].push(hit);saveLists();refreshLists(name);status.textContent='„'+hit.title+'“ wurde zu „'+name+'“ hinzugefügt.'}
function show(hits){lastHits=hits;results.innerHTML='';hits.forEach(hit=>{const el=document.createElement('article');el.className='hit';el.innerHTML='<h3>'+esc(hit.title||'(ohne Titel)')+'</h3><div class="meta">'+esc([hit.providerLabel||hit.source?.label,hit.type,hit.key&&'Tonart '+hit.key,hit.meter&&'Takt '+hit.meter].filter(Boolean).join(' · '))+'</div><div class="actions"><button class="play">▶ Vorhören</button><button class="stop">■ Stop</button><button class="add">＋ Zur Liste</button></div><div class="preview"></div>';const formatText=(hit.availableFormats||Object.keys(hit.formats||{})).map(x=>x==='musicxml'?'MusicXML':x==='lilypond'?'LilyPond':x.toUpperCase()).join(' · ');if(formatText){const f=document.createElement('div');f.className='meta';f.textContent='Dateien: '+formatText;el.querySelector('.meta').after(f)}const box=el.querySelector('.preview'),play=el.querySelector('.play');if(play){play.onclick=()=>previewHit(hit,box,play).catch(e=>{console.error(e);status.textContent='Vorhörfehler: '+(e?.message||String(e)||'Unbekannter Fehler')});el.querySelector('.stop').onclick=async()=>{await stop();play.textContent='▶ Vorhören'}}else{el.querySelector('.source').onclick=()=>window.open(hit.source?.lilypondUrl||hit.source?.pdfUrl,'_blank')}el.querySelector('.add').onclick=()=>add(hit);results.appendChild(el)})}
async function run(){try{saveMemory();await stop();results.innerHTML='';status.textContent='Datenbank laden / suchen …';const selected=[...document.querySelectorAll('[data-source]:checked')].map(x=>x.value),available=new Set(engine.listProviders().map(x=>x.id)),sources=selected.filter(id=>available.has(id));if(!sources.length){const pending=selected.length?'Die ausgewählten Quellen sind noch nicht als Suchprovider angeschlossen. Bitte eine aktive Suchquelle auswählen.':'Keine Suchquelle ausgewählt.';throw new Error(pending)}const hits=await engine.search($('query').value,{type:$('type').value,key:$('key').value,meter:$('meter').value,limit:100},sources);show(hits);saveMemory();status.textContent=hits.length+' Treffer (max. 100).'}catch(e){status.textContent='Suchfehler: '+e.message}}
$('search').onclick=run;$('query').addEventListener('keydown',e=>{if(e.key==='Enter')run()});for(const id of['query','type','key','meter','instrument'])$(id).addEventListener('change',saveMemory);function updateSourceCount(){const boxes=[...document.querySelectorAll('[data-source]')],n=boxes.filter(x=>x.checked).length,active=boxes.filter(x=>!x.disabled&&x.checked).length;$('sourceCount').textContent=n+' ausgewählt'+(n>active?' · '+active+' aktiv':'')}document.querySelectorAll('[data-source]').forEach(x=>x.addEventListener('change',()=>{updateSourceCount();saveMemory()}));$('allSources').onclick=()=>{document.querySelectorAll('[data-source]').forEach(x=>x.checked=!x.disabled);updateSourceCount();saveMemory()};$('noSources').onclick=()=>{document.querySelectorAll('[data-source]').forEach(x=>x.checked=false);updateSourceCount();saveMemory()};$('clear').onclick=()=>{for(const id of['query','type','key','meter'])$(id).value='';saveMemory()};
$('createList').onclick=()=>{const n=$('newList').value.trim();if(!n)return;lists[n]??=[];saveLists();$('newList').value='';refreshLists();$('listSelect').value=n;refreshLists()};$('listSelect').onchange=()=>{refreshLists($('listSelect').value);saveMemory()};
$('exportList').onclick=()=>{const n=$('listSelect').value;if(!n)return;const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify({name:n,items:lists[n]},null,2)],{type:'application/json'}));a.download=n.replace(/[^a-z0-9_-]+/gi,'_')+'.json';document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},500)};
$('importButton').onclick=()=>$('importFile').click();$('importFile').onchange=async e=>{try{const f=e.target.files[0];if(!f)return;const d=JSON.parse(await f.text());if(!d.name||!Array.isArray(d.items))throw new Error('Ungültige Listendatei.');lists[d.name]=d.items;saveLists();refreshLists();$('listSelect').value=d.name;refreshLists();status.textContent='Liste „'+d.name+'“ geladen.'}catch(err){status.textContent='Importfehler: '+err.message}e.target.value=''};for(const id of['query','type','key','meter'])if(memory[id]!=null)$(id).value=memory[id];$('instrument').innerHTML=instruments.map(x=>'<option value="'+x[0]+'">'+x[1]+'</option>').join('');$('instrument').value=memory.instrument&&instruments.some(x=>x[0]===memory.instrument)?memory.instrument:'auto';const rememberedSources=Array.isArray(memory.sources)?[...new Set([...memory.sources,'musetrainer'])]:['thesession','gavin','musetrainer'];document.querySelectorAll('[data-source]').forEach(x=>x.checked=!x.disabled&&rememberedSources.includes(x.value));updateSourceCount();refreshLists(memory.activeList);if(Array.isArray(memory.lastHits)&&memory.lastHits.length){show(memory.lastHits);status.textContent=memory.lastHits.length+' Treffer der letzten Suche wiederhergestellt.'}
let vrvToolkit=null;
async function ensureVerovio(){
 if(vrvToolkit)return vrvToolkit;
 if(typeof verovio==='undefined'){
  await new Promise((resolve,reject)=>{
   const script=document.createElement('script');
   script.src='https://www.verovio.org/javascript/latest/verovio-toolkit-wasm.js';
   script.onload=resolve;
   script.onerror=()=>reject(new Error('Verovio-Skript konnte nicht geladen werden.'));
   document.head.appendChild(script);
  });
 }
 if(typeof verovio==='undefined'||!verovio.module)throw new Error('Verovio wurde geladen, aber nicht initialisiert.');
 if(!(verovio.module.calledRun||verovio.module.runtimeInitialized)){
  await new Promise((resolve,reject)=>{
   const timer=setTimeout(()=>reject(new Error('Verovio-Initialisierung dauert zu lange.')),20000);
   verovio.module.onRuntimeInitialized=()=>{clearTimeout(timer);resolve();};
  });
 }
 vrvToolkit=new verovio.toolkit();
 return vrvToolkit;
}
